### ISSUE TITLE
[Tracking] Gems / plugins replacements

### ISSUE THREAD

**Issue by jnv** [crewmate/crewmate#64]
Lot of gems in Gemfile are obsolete and abandoned, so this is the place to keep track and discuss what to replace them with.
- [ ] **#58** [tmail](http://tmail.rubyforge.org/) → [mail](https://github.com/mikel/mail) 
  - recommended by the tmail author
- [ ] [vestal_versions](https://github.com/adamcooper/vestal_versions) → [PaperTrail](https://github.com/airblade/paper_trail)
  - used for versioning Notes and Dividers (wat.)
  - [other options](https://www.ruby-toolbox.com/categories/Active_Record_Versioning)
- [ ] [permalink_fu](https://github.com/teambox/permalink_fu) (TB fork) → ?
  - [options](https://www.ruby-toolbox.com/categories/rails_permalinks___slugs)
  - Causes #78
- [ ] [cancan](https://github.com/ryanb/cancan) – just update
- [ ] **#61** [immortal](https://github.com/davidmm/immortal) → [acts_as_paranoid](https://github.com/goncalossilva/acts_as_paranoid) 
  - [other options](https://www.ruby-toolbox.com/categories/Active_Record_Soft_Delete)
- [ ] [Hpricot](https://github.com/hpricot/hpricot) → [Nokogiri](http://www.nokogiri.org/) (probably could replace libxml-ruby too)
- [ ] [Rdiscount](https://github.com/davidfstr/rdiscount) → keep it or [redcarpet](https://github.com/vmg/redcarpet) (though I really hate it for a lack of support for localization of smart quotes)
  - [other options](https://www.ruby-toolbox.com/categories/markup_processors) (keep Markdown)
- [ ] **#37** `net-ldap`, `oa-oauth` + custom authentication → Devise + OmniAuth
  - this will also require rewrite of invitation system and Google Drive integration
- [ ] **#14** `jammit`, `barista` → `sprockets`
- [ ] `will_paginate` → just update
- [ ] [Thinking Sphinx](http://pat.github.io/thinking-sphinx/) → just update?
  - [other options](https://www.ruby-toolbox.com/categories/rails_search)
- [ ] [choices](https://github.com/teambox/choices/) → ? (original is not much better)
# vendor/plugins
- [rspec-on-rails-matchers](https://github.com/joshknowles/rspec-on-rails-matchers) → [Shoulda](https://github.com/thoughtbot/shoulda-matchers)
- asset-hosting-with-minimum-ssl
- dynamic_form
- email-spec
- localized_country_select
- mail_view
- mimetype-fu
- rails_upgrade
- restful-authentication
- tabnav
- view_specify

What else?
